# Generated by Django 4.0.5 on 2022-06-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phot',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
