# Generated by Django 4.0.5 on 2022-10-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_seller_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_name',
            new_name='seller_id',
        ),
    ]
